all:
	python plot_resnet18_test_accuracy.py
	python plot_resnet18_stiefel_distances.py
	python plot_vgg16_test_accuracy.py
	python plot_vgg16_stiefel_distances.py
	python plot_pca_train_loss.py
	python plot_pca_stiefel_distances.py
	zsh crop.sh